blog/urls.py
"""
    Defines the URL patterns for the blog app.
"""
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    # Home page.
    path('', views.index, name='index'),

    # Blog page listing article snippets.
    path('blog/', views.blog, name='blog'),

    # Blog detail view - shows the full article detail.
    path('blog/article/<slug:slug>', views.article_detail, name='article_detail'),

    # Articles created by the current user only.
    path('blog/my-articles', views.user_articles, name='user_articles'),

    # Add new article
    path('blog/add-article', views.add_article, name='add_article'),

    # Edit article
    path('blog/edit-article/<slug:slug>', views.edit_article, name='edit_article'),

    # Delete article
    path('blog/delete-article/<slug:slug>', views.delete_article, name='delete_article')
]

blog_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

users/urls.py
"""
    Defines the URL patterns for users.
"""
from django.urls import path, include


app_name = 'users'
urlpatterns = [
    # Default auth urls.
    path('', include('django.contrib.auth.urls')),
]

blog/models.py
import os
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Article(models.Model):
    """
    A class to represent users articles.

    Attributes
    ----------
    self.title : str
        title of users article.
    self.body : str
        article/blog content.
    self.date : date
        time and date of article submission.
    self.slug : str
        Pretty URL slugs for blog pages.
    self.author : user
        name of the user who created the article.
    self.image : ImageField
        Image uploaded by user.
    self.image_alt : str
        Image ALT tag for HTML templates.


    Methods
    -------
    create_path:
        returns a path to the users media directory.

    _create_img_filename:
        returns a new image filename before saving relating to its content.

    ___str___():
        returns a string representation of the model.

    snippet():
        returns a string snippet with ellipsis.

    get_absolute_url():
        returns a URL using a 'slug' as its key
    """

    def create_path(instance, filename):
        """ Returns the path to save users image.  """

        # Rename image filename.
        filename = instance._create_img_filename(filename)

        # Create path to image.
        path = os.path.join('users/' + instance.author.username, 'images/', filename)
        return path

    def _create_img_filename(self, filename):
        """ Rename the uploaded image relating to the content.
            Returns the new filename.
        """
        # Get the image extension
        ext = filename.split('.')[-1]

        # Create filename base on the slug and add the extension.
        filename = f'{self.slug}.{ext}'
        return filename

    title = models.CharField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=50, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=create_path, blank=True)
    image_alt = models.CharField(max_length=125)

    def __str__(self):
        """ Returns a string representation of the model. """
        return self.title

    def snippet(self):
        """ Return a string snippet plus ellipsis. """
        snippet = f"{self.body[:150]}..."
        return snippet

    def get_absolute_url(self):
        """ returns the URL for the requested article. """
        return reverse('blog:article_detail', kwargs={'slug': self.slug})

users/models.py
from django.db import models

# Create your models here.

blog/forms.py
"""
    Using ModelForm to automatically build a form using the information
    from the models defined in models.py
"""

from django import forms

from .models import Article


class AddArticleForm(forms.ModelForm):
    """ Automatically build a form using the information from supplied model. """

    class Meta:
        model = Article
        fields = ['title', 'body', 'slug', 'image', 'image_alt']
        labels = {'slug': 'URL description', 'image_alt': 'Image description'}


class EditArticleForm(AddArticleForm):
    """ Automatically build a form using the information from the supplied model. """

blog/views.py
import os

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Article
from .forms import AddArticleForm, EditArticleForm


def index(request):
    """ The home page for users blog articles. """
    return render(request, 'index.html')


def blog(request):
    """ Show a snippet of all blog articles. """
    # Get all articles and sort by date added.
    articles = Article.objects.order_by('-date')
    context = {'articles': articles}
    return render(request, 'blog.html', context)


def article_detail(request, slug):
    """ Show the full article. """
    article = Article.objects.get(slug=slug)
    context = {'article': article}
    return render(request, 'article_detail.html', context)


@login_required
def add_article(request):
    """ Add a new article. """
    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = AddArticleForm()
    else:
        # POST data submitted, process data.
        form = AddArticleForm(request.POST, request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.author = request.user
            new_article.save()
            return back_to_blog_page()

    context = {'form': form}
    return render(request, 'add_article.html', context)


@login_required
def edit_article(request, slug):
    """ Edit an existing article. """
    article = Article.objects.get(slug=slug)

    # Check that the current user has permission to edit the article.
    check_user(request, article)

    if request.method != 'POST':
        # Initial request pre-populate form with current article content.
        form = EditArticleForm(instance=article)
    else:
        # POST data submitted, process data.
        form = EditArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return back_to_blog_page()

    context = {'article': article, 'form': form}
    return render(request, 'edit_article.html', context)


@login_required
def delete_article(request, slug):
    """ Delete an existing article. """
    article = Article.objects.get(slug=slug)

    # Check that the current user has permission to delete the article.
    check_user(request, article)

    # Check if article contains image and remove.
    if os.path.isfile(article.image.path):
        os.remove(article.image.path)

    # Goodbye ;)
    article.delete()
    return back_to_blog_page()


@login_required
def user_articles(request):
    """ Show articles created by the user only. """
    articles = Article.objects.filter(author=request.user).order_by('-date')
    context = {'articles': articles}
    return render(request, 'user_articles.html', context)


def back_to_blog_page():
    """ returns the appropriate url the arguments passed. """
    return redirect('blog:blog')


def check_user(request, article):
    """
        Protect the users article.
        If user tries to retrieve articles they do not own raise http404 exception.
    """
    if article.author != request.user:
        print(f"Permission Denied: {request.user} does not have permission to access this article.")
        raise Http404
    else:
        return

users/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/add_article.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Add article{% endblock title %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Create new article</h1>
        <p class="lead">You are limited by your own imagination... Let if fly.</p>
    </div>
{% endblock page_header %}

{% block content %}
    <form enctype="multipart/form-data" method="post" action="{% url 'blog:add_article' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit_article" class="btn btn-primary">Publish article</button>
        {% endbuttons %}
    </form>
{% endblock content %}

blog/templates/article_detail.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock title %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">{{ article.title }}</h1>
        <p class="lead">Written by {{ article.author.get_full_name }}</p>
        <p class="lead">{{ article.date|date:'M d, Y'}}</p>
    </div>

{% endblock page_header %}

{% block content %}

        {% if article.image %}
            <img class="img-responsive" src="{{ article.image.url }}" alt="{{ article.image_alt }}"
                 height="auto" width="100%">
        {% endif %}

    <p class="lead">{{ article.body }}</p>
{% endblock content %}

blog/templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'blog:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%  url 'blog:blog' %}">Blog</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello {{ user.get_full_name }}.</span>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:user_articles' %}">Manage articles</a></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a></a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>

    <div>
        {% block content %}{% endblock content %}
    </div>

</main>
</body>
</html>

blog/templates/blog.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock title %}

{% block page_header %}
        <div class="jumbotron">
        <h1 class="display-3">Blog posts</h1>
        </div>
{% endblock page_header %}

{% block content %}
    {% for article in articles %}
        <div class="card border-info mb-3">
            <img src="" class="card-img" alt="">
            <div class="card-header">{{ article.date|date:'M d, Y'}}
                <span style="float: right">Written by {{ article.author.get_full_name.title }}</span>
            </div>
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <p class="card-text">{{ article.snippet }}</p>
                    <a href="{{ article.get_absolute_url }}" class="btn btn-primary">Continue reading &raquo;</a>
                </div>
        </div>

    {% endfor %}
{% endblock content %}

blog/templates/edit_article.html
{% extends 'base.html' %}

{% block title %}Edit article{% endblock title %}

{% block page_header %}
    <h1 class="display-3">Edit article.</h1>
{% endblock page_header %}

{% block content %}
    <form enctype="multipart/form-data" method="post" action={% url 'blog:edit_article' article.slug %}>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
{% endblock content %}

blog/templates/index.html
{% extends "base.html" %}

{% block title %}Homepage{% endblock title %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Welcome to the blog site project.</h1>

        <p class="lead">Welcome to the blog site project powered by django.</p>
        <a class="btn btn-lg btn-primary" href="{% url 'blog:blog' %}" role="button">View blog &raquo;</a>
    </div>
{% endblock page_header %}

{% block content %}
    <p>The blog site project was created using python and the django framework.  The project was created purely as a
        learning exercise to explore the django framework and bootstrap components.
    </p>
{% endblock content %}

blog/templates/user_articles.html
{% extends 'base.html' %}
{% block title %}My Posts{% endblock title %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">My articles</h1>

        <p class="lead">Hello, {{ user.first_name.title }}.  Are you feeling creative?</p>
        <a class="btn btn-lg btn-primary" href="{% url 'blog:add_article' %}" role="button">Add new article &raquo;</a>
    </div>
{% endblock page_header %}

{% block content %}
    {% for article in articles %}
        <p>
            <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
            {% if user.is_authenticated %}:
                <a href="{% url 'blog:edit_article' article.slug %}">[Edit]</a> -
                <a href="{% url 'blog:delete_article' article.slug %}">[Delete]</a>
            {% endif %}
        </p>
    {% endfor %}
{% endblock content %}